name: Deploy to dev
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Start SSH agent
        run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "$DEPLOY_KEY")
          echo "$PASSPHRASE" | ssh-add -
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd /var/www/app-be 
            git pull origin master
            npm ci
            pm2 restart app-be-dev

    
