name: Deploy to production
on:
  push:
    tags:
      - v*
  workflow_dispatch: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        env:
          PORT: ${{ secrets.PORT_BE_PROD }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          envs: PORT
          script: |
            cd /var/www/app-be 
            git pull origin master
            npm ci
            pm2 restart app-be || pm2 start index.js --name app-be 
            pm2 save

        
  
