name: Deploy to production
on:
  push:
    tags:
      - v*
  workflow_dispatch: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.PROD_ENV }}" > .env
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/app-be 
            git pull origin master
            npm ci
            pm2 restart app-be || pm2 start index.js --name app-be 
            pm2 save

        
  
