name: Deploy to production
on:
  push:
    tags:
      - v*
  workflow_dispatch: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: 'Checkout repository'
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
      - run: printf "${{ secrets.PORT }}" >> .env
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: unnecessary
          name: gh_key
          config: |
            StrictHostKeyChecking no
      - run: ssh damarvijis@damarvijis.com "cd /var/www/app-be && pm2 restart app-be || pm2 start --name app-be-dev node index.js --port 8080"
        
  
